# taken from https://github.com/uclaacm/teach-la-ts-react-starter/blob/608c973d9f9af3d29eff41a97e60069af726463a/.github/workflows/build.yml
name: Production Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install

      - run: yarn build
        env:
          EVENTS_SPREADSHEET_ID: ${{ secrets.EVENTS_SPREADSHEET_ID }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CI: true
          DIRECTORY_SPREADSHEET_ID: ${{secrets.DIRECTORY_SPREADSHEET_ID }}
          LANDING_SPREADSHEET_ID: ${{secrets.LANDING_SPREADSHEET_ID }}
